name: aci-privateagents-kv-integration
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src/terraform/*
      - src/pipelines/*

resources:
  - repo: self

variables:
  - name: tag
    value: "$(Build.BuildId)"
  - group: TFBackend
  - group: ACIDevOps.Secrets
  - name: skipComponentGovernanceDetection
    value: true
  - name: vmImageName
    value: "ubuntu-latest"
  - name: terraformVersion
    value: 0.12.24

stages:
  - stage: DeployInfra
    displayName: Deploy Infra
    jobs:
      - job: DeployInfra
        displayName: Deploy Infra
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
            displayName: "Use Terraform $(terraformVersion)"
            inputs:
              terraformVersion: $(terraformVersion)
          - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
            displayName: "terraform init"
            inputs:
              command: init
              commandOptions: "-backend=true -backend-config=$(System.DefaultWorkingDirectory)/src/pipelines/backend.azure.tf"
              backendType: azurerm
              backendServiceArm: $(service_connection)
              ensureBackend: true
              backendAzureRmResourceGroupLocation: $(location)
              backendAzureRmResourceGroupName: $(backendStorageResourceGroupName)
              backendAzureRmStorageAccountName: $(backendStorageAccountName)
              backendAzureRmStorageAccountSku: $(backendStorageAccountSKU)
              backendAzureRmContainerName: $(backendContainerName)
              backendAzureRmKey: "$(Build.DefinitionName)/tfstate-$(tag)"
              workingDirectory: "$(System.DefaultWorkingDirectory)/src/terraform"
          - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
            displayName: "terraform validate"
            inputs:
              workingDirectory: "$(System.DefaultWorkingDirectory)/src/terraform"
          - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
            displayName: "terraform plan"
            inputs:
              command: plan
              environmentServiceName: $(service_connection)
              workingDirectory: "$(System.DefaultWorkingDirectory)/src/terraform"
              commandOptions: "-var resource_group_name=$(Build.DefinitionName) -var suffix=$(tag) -var devops_org_name=$(devopsOrganization) -var devops_personal_access_token=$(devopsPersonalAccessToken) -var devops_pool_name=$(devopsPoolName) -var devops_agent_docker_image=$(devopsAgentDockerImage) -var devops_agent_docker_tag=$(devopsAgentDockerTag)"
          - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
            displayName: "terraform apply"
            inputs:
              command: apply
              environmentServiceName: $(service_connection)
              workingDirectory: "$(System.DefaultWorkingDirectory)/src/terraform"
              commandOptions: "-var resource_group_name=$(Build.DefinitionName) -var suffix=$(tag) -var devops_org_name=$(devopsOrganization) -var devops_personal_access_token=$(devopsPersonalAccessToken) -var devops_pool_name=$(devopsPoolName) -var devops_agent_docker_image=$(devopsAgentDockerImage) -var devops_agent_docker_tag=$(devopsAgentDockerTag)"
          - bash: |
              ACCESSPOLICYID=`terraform output accesspolicyid`
              KEYVAULTID=`terraform output keyvaultid`
              echo "##vso[task.setvariable variable=KEYVAULTID]$KEYVAULTID"              
              echo "##vso[task.setvariable variable=ACCESSPOLICYID]$ACCESSPOLICYID"
            displayName: "terraform output"
            workingDirectory: "$(System.DefaultWorkingDirectory)/src/terraform"
          - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
            displayName: "terraform init delete access policy"
            inputs:
              command: init
              workingDirectory: "$(System.DefaultWorkingDirectory)/src/terraform/delete_access_policy"
          - task: AzureCLI@2
            displayName: "Terraform import"
            inputs:
              azureSubscription: $(service_connection)
              workingDirectory: "$(System.DefaultWorkingDirectory)/src/terraform/delete_access_policy"
              scriptType: bash
              scriptLocation: inlineScript
              addSpnToEnvironment: true
              inlineScript: |
                # https://github.com/terraform-providers/terraform-provider-azurerm/issues/3814#issuecomment-512573065
                export ARM_CLIENT_ID=$servicePrincipalId
                export ARM_CLIENT_SECRET=$servicePrincipalKey
                export ARM_SUBSCRIPTION_ID=$(az account show --query id | xargs)
                export ARM_TENANT_ID=$(az account show --query tenantId | xargs)
                terraform import -var key_vault_id=$KEYVAULTID azurerm_key_vault_access_policy.current $(ACCESSPOLICYID)
          - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
            displayName: "terraform plan"
            inputs:
              command: plan
              backendType: local
              environmentServiceName: $(service_connection)
              workingDirectory: "$(System.DefaultWorkingDirectory)/src/terraform/delete_access_policy"
              commandOptions: "-var key_vault_id=$(KEYVAULTID)"
          - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
            displayName: "terraform apply delete access policy"
            inputs:
              command: apply
              backendType: local
              environmentServiceName: $(service_connection)
              workingDirectory: "$(System.DefaultWorkingDirectory)/src/terraform/delete_access_policy"
              commandOptions: "-var key_vault_id=$(KEYVAULTID)"
